# Generated by Django 4.2.11 on 2024-03-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
                ('request_complete', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
        migrations.CreateModel(
            name='FriendRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.IntegerField()),
                ('request_status', models.IntegerField(default='0')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media_app.userregistration')),
            ],
            options={
                'db_table': 'tbl_friend_request_status',
            },
        ),
    ]
